action file updated

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,4 +1,3 @@
-
 name: Indigenous connect frontend CI
 
 on:
@@ -14,7 +13,7 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [22.x]
+        node-version: [20.x]  
 
     steps:
     - uses: actions/checkout@v4
@@ -25,7 +24,6 @@ jobs:
         node-version: ${{ matrix.node-version }}
         cache: 'pnpm'
 
-
     - name: Copy environment files
       run: |
         cp ~/env/frontend/.env ./
@@ -35,5 +33,10 @@ jobs:
       run: pnpm install
 
     - name: Build project
-      run: pnpm run build 
+      run: pnpm run build
 
+    - name: Debug Build Logs
+      run: cat .next/build-manifest.json || echo "Build manifest not found"
+
+    - name: Restart the app using pm2 
+      run: pm2 restart ic-frontend
